### PR TITLE
Adding Get Package Dependencies

### PR DESCRIPTION
**Pull request by eisenwr**
#5 
Adding Get Package Dependencies
Refactoring common code into _support

### CODE REVIEW

**Comment by allenh-ni** [comment]
@eisenwr - Are you able to make the following changes?

- For the Get Package Dependencies VI, please go to File>VI Properties.  And in Window Appearance category, please disable the "Same as VI name" checkbox and manually type "Get Package Dependencies" into the Window title textbox.

- Can you use VIPM 2014 to modify the VIPB file and generate the VIP package?  I think you used VIPM 2017, so I wasn't able to install your package (or view the VIPB file) with LabVIEW 2014 and VIPM 2014.  If you are unable to, just let me know and I will make these changes on my end.

Thanks for the contribution!

**Comment by eisenwr** [comment]
@allenh-ni 
Sorry I always forget that VIPM does not allow older version to open the .vipb. Luckily I did still have an archived installer for 2014. I was able to do both requested changes.

**Comment by allenh-ni** [comment]
@eisenwr - Your changes look great.  Can you make one last quick change?

- Please edit the .vipb file, so that the Version Number is 3.2.0.8.  Since you are adding functionality (Get Package Dependencies VI) in a backwards compatible manner, I'd like to increment the Minor version from 1 to 2.  And you can let the Build Number continue to increment to 8.

- Replace your v3.1.0.7 package (.vip) with your newly built v3.2.0.8 package (.vip)

I'll merge the pull request afterwards.

**Comment by eisenwr** [comment]
@allenh-ni 
I have rebuilt with the new requested minor version number.

**Comment by allenh-ni** [comment]
@eisenwr - Thanks for adding the Get Package Dependencies to the NIPM API!  I've merged the pull request.

**Pull request merged**
