### PR TITLE
Add glob

### PR DESCRIPTION
**Pull request by eisenwr**
I wanted to add the ability to filter the packages returned by the list operations. Could you please give me feedback on this example before I replicate to the other methods.

### CODE REVIEW

**Comment by allenh-ni** [comment]
Thanks for adding a new "package name filter" to the API!

Feedback
1.  Can you change the "Package Name Filter" control label to be lowercase "package name filter"?
2. Can you change the "package name filter" input to be an optional input instead of recommended since it seems like an advanced use case?
3. Can you change the "package name filter" input's description in the Context Help to be "Package name filter: Specifies the glob pattern (e.g. package-abc1, package-abc2, package-abc*, *abc*) used to filter the returned list of packages.  If empty, this VI will return an unfiltered list of packages."

**Comment by eisenwr** [comment]
@allenh-ni 
I have updated per your feedback. Can you confirm that it correct before I add the same to List Installed Packages and List Upgradable Packages?

**Comment by allenh-ni** [comment]
Almost done.  Your VI description is currently (has a duplicate input name on the line):
**Package Name Filter**: Package name filter: Specifies the glob pattern...

Please change it to:
**Package name filter**: Specifies the glob pattern...

**Comment by eisenwr** [comment]
@allenh-ni 
I have updated the description per your comment.

**Comment by eisenwr** [comment]
@allenh-ni 
Also I have replicated the package name filter to List Installed Packages and List Upgradable Packages

**Comment by allenh-ni** [comment]
Merged your pull request.  Thanks for adding the "package filter" functionality!

**Pull request merged**
